=== Pecsj/note/j2ee知识点/3filter,listener,xml,session/付费一阶段第73课---JDOM和DOM4J解析XML文件/代码/TestXML/out/production/TestXML/testxml/myxml.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT school (class*)>
<!ELEMENT class (teacher,student*)>
<!ELEMENT teacher (sex)>
<!ELEMENT student (sex)>
<!ELEMENT sex (#PCDATA)>

<!ATTLIST school
    id CDATA #IMPLIED
    name CDATA #IMPLIED
    loc CDATA #IMPLIED
>
<!ATTLIST class
    id CDATA #IMPLIED
    name CDATA #IMPLIED
    loc CDATA #IMPLIED
>
<!ATTLIST teacher
    id CDATA #IMPLIED
    name CDATA #IMPLIED
    age CDATA #IMPLIED
>
<!ATTLIST student
    id CDATA #IMPLIED
    name CDATA #IMPLIED
    age CDATA #IMPLIED
>

=== Pecsj/note/j2ee知识点/3filter,listener,xml,session/付费一阶段第75课---XML之DTD规则/代码/TestXML/src/testxml/school.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE school SYSTEM "myxml.dtd">

<school id="xxx" name="" loc="">
    <class id="" name="" loc="">
        <teacher id="" name="" age="">
            <sex>男</sex>
        </teacher>
        <student id="" name="" age="">
            <sex>女</sex>
        </student>
        <student>
            <sex></sex>
        </student>
        <student>
            <sex></sex>
        </student>
    </class>
    <class>
        <teacher>
            <sex></sex>
        </teacher>
        <student>
            <sex></sex>
        </student>
        <student>
            <sex></sex>
        </student>
        <student>
            <sex></sex>
        </student>
    </class>
</school>

=== Pecsj/note/j2ee知识点/3filter,listener,xml,session/付费一阶段第73课---JDOM和DOM4J解析XML文件/代码/TestXML/src/testxml/school.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE school SYSTEM "myxml.dtd">

<school id="duyi" name="渡一教育" loc="哈尔滨">
    <class id="one" name="Java1期" loc="上海">
        <teacher id="t1" name="zzt" age="18">
            <sex>男</sex>
        </teacher>
        <student id="s1" name="赵一" age="15">
            <sex>女</sex>
        </student>
        <student id="s2" name="钱二" age="16">
            <sex>女</sex>
        </student>
        <student id="s3" name="孙三" age="17">
            <sex>男</sex>
        </student>
        <student id="s4" name="李四" age="18">
            <sex>男</sex>
        </student>
    </class>
    <class id="two" name="Java2期" loc="深圳">
        <teacher id="t2" name="panda" age="58">
            <sex>纯爷们儿</sex>
        </teacher>
        <student id="s5" name="周五" age="18">
            <sex>男</sex>
        </student>
        <student id="s6" name="吴六" age="17">
            <sex>男</sex>
        </student>
        <student id="s7" name="郑七" age="16">
            <sex>女</sex>
        </student>
        <student id="s8" name="王ba" age="15">
            <sex>女</sex>
        </student>
    </class>
</school>
